"""Event definitions — topic names and Pydantic message schemas."""

from .topics import (
    # pipeline
    IMAGE_UPLOADED,
    INFERENCE_COMPLETED,
    DOCUMENT_STORED,
    VECTOR_COMPUTED,
    EMBEDDING_INDEXED,
    # search
    SEARCH_REQUESTED,
    VECTOR_SEARCH_REQUESTED,
    SEARCH_COMPLETED,
    # read request/reply
    DOCUMENTS_LIST_REQUESTED,
    DOCUMENTS_LIST_COMPLETED,
    DOCUMENT_GET_REQUESTED,
    DOCUMENT_GET_COMPLETED,
    EMBEDDING_GET_REQUESTED,
    EMBEDDING_GET_COMPLETED,
    SCHEMAS_LIST_REQUESTED,
    SCHEMAS_LIST_COMPLETED,
    SCHEMA_CREATE_REQUESTED,
    SCHEMA_CREATE_COMPLETED,
    STATS_REQUESTED,
    STATS_COMPLETED,
    VOCABULARY_REQUESTED,
    VOCABULARY_COMPLETED,
    EMBED_TEXT_REQUESTED,
    EMBED_TEXT_COMPLETED,
    EMBED_TAGS_REQUESTED,
    EMBED_TAGS_COMPLETED,
    ALL_TOPICS,
)
from .schemas import (
    EventEnvelope,
    # pipeline
    ImageUploadedPayload,
    InferenceCompletedPayload,
    DocumentStoredPayload,
    VectorComputedPayload,
    EmbeddingIndexedPayload,
    # search
    SearchRequestedPayload,
    VectorSearchRequestedPayload,
    SearchCompletedPayload,
    SearchHit,
    # read request/reply
    DocumentsListRequestedPayload,
    DocumentsListCompletedPayload,
    DocumentGetRequestedPayload,
    DocumentGetCompletedPayload,
    EmbeddingGetRequestedPayload,
    EmbeddingGetCompletedPayload,
    SchemaSpec,
    SchemasListRequestedPayload,
    SchemasListCompletedPayload,
    SchemaCreateRequestedPayload,
    SchemaCreateCompletedPayload,
    StatsRequestedPayload,
    StatsCompletedPayload,
    VocabularyCategory,
    VocabularyRequestedPayload,
    VocabularyCompletedPayload,
    EmbedTextRequestedPayload,
    EmbedTagsRequestedPayload,
    EmbedCompletedPayload,
    make_event,
    validate_payload,
)

__all__ = [
    # pipeline topics
    "IMAGE_UPLOADED",
    "INFERENCE_COMPLETED",
    "DOCUMENT_STORED",
    "VECTOR_COMPUTED",
    "EMBEDDING_INDEXED",
    # search topics
    "SEARCH_REQUESTED",
    "VECTOR_SEARCH_REQUESTED",
    "SEARCH_COMPLETED",
    # read request/reply topics
    "DOCUMENTS_LIST_REQUESTED",
    "DOCUMENTS_LIST_COMPLETED",
    "DOCUMENT_GET_REQUESTED",
    "DOCUMENT_GET_COMPLETED",
    "EMBEDDING_GET_REQUESTED",
    "EMBEDDING_GET_COMPLETED",
    "SCHEMAS_LIST_REQUESTED",
    "SCHEMAS_LIST_COMPLETED",
    "SCHEMA_CREATE_REQUESTED",
    "SCHEMA_CREATE_COMPLETED",
    "STATS_REQUESTED",
    "STATS_COMPLETED",
    "VOCABULARY_REQUESTED",
    "VOCABULARY_COMPLETED",
    "EMBED_TEXT_REQUESTED",
    "EMBED_TEXT_COMPLETED",
    "EMBED_TAGS_REQUESTED",
    "EMBED_TAGS_COMPLETED",
    "ALL_TOPICS",
    # envelope
    "EventEnvelope",
    "make_event",
    "validate_payload",
    # pipeline payloads
    "ImageUploadedPayload",
    "InferenceCompletedPayload",
    "DocumentStoredPayload",
    "VectorComputedPayload",
    "EmbeddingIndexedPayload",
    # search payloads
    "SearchRequestedPayload",
    "VectorSearchRequestedPayload",
    "SearchCompletedPayload",
    "SearchHit",
    # read request/reply payloads
    "DocumentsListRequestedPayload",
    "DocumentsListCompletedPayload",
    "DocumentGetRequestedPayload",
    "DocumentGetCompletedPayload",
    "EmbeddingGetRequestedPayload",
    "EmbeddingGetCompletedPayload",
    "SchemaSpec",
    "SchemasListRequestedPayload",
    "SchemasListCompletedPayload",
    "SchemaCreateRequestedPayload",
    "SchemaCreateCompletedPayload",
    "StatsRequestedPayload",
    "StatsCompletedPayload",
    "VocabularyCategory",
    "VocabularyRequestedPayload",
    "VocabularyCompletedPayload",
    "EmbedTextRequestedPayload",
    "EmbedTagsRequestedPayload",
    "EmbedCompletedPayload",
]
